dist: trusty

sudo: require

notifications:
  email:
    recipients:
        - weymouth@umich.edu
    on_success: change
    on_failure: always

# blocklist - branches not used for testing: any branch starting with 'spike'
branches:
  except:
  - /^spike-.*$/

language: python

python:
  - 2.7

addons:
  hosts:
  - mctest.localhost

env:
  global:
    - MCDIR=/tmp/mcdir
    - MCDB_TYPE=rethinkdb
    - MCDB_NAME=materialscommons
    - MCDB_FILE=test_data/test_ready_rethinkdb_dump_2016-12-15.tar.gz
    - MCDB_PORT=30815
    - MC_LOG_DIR=/tmp
    - SERVERTYPE=travisrun
    - MCDB_CONNECTION=localhost:$MCDB_PORT
    - MCAPI_SERVER_PORT=5004
    - MC_SERVICE_PORT=5000
    - RETHINKDB_CLUSTER_PORT=31815
    - RETHINKDB_HTTP_PORT=8090
    - MC_DOI_SERVICE_URL=https://ezid.lib.purdue.edu/
    - MC_DOI_PUBLISHER='Materials Commons'
    - MC_DOI_PUBLICATION_BASE=http://mcpub.localhost/#/details
    - MC_DOI_NAMESPACE='doi:10.5072/FK2'

git:
  depth: 3

before_install:
    # RethinkDB
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
    # Yarn
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update
  - sudo cat /etc/hosts

install:
  - nvm install v6.10
  - node --version
  - sudo apt-get install nginx
  - sudo apt-get install rethinkdb
  - sudo apt-get install yarn

  - pushd ~
  - npm install -g node-gyp@3.5.0
  - npm install -g gulp
  - mkdir .materialscommons
  - git clone -b sprint --depth 3 https://github.com/materials-commons/materialscommons.org.git

  - pushd materialscommons.org
  - git log -1
  - export MC_CLONE_DIR=`pwd`
  - yarn install

  - pushd backend
  - pip install rethinkdb
  - pip install Flask
  - pip install pytest
  - pip install pbkdf2
  - popd

  - popd

  - popd

  - cd python
  - export MC_PYTHON_API_DIR=`pwd`
  - pip install -r requirements.txt
# Note: github does not store or recover empty directories
#       this is needed for testing - creating empty dir
  - mkdir -p test/test_data/test_upload_data/test_upload_dir/sub_directory_c/empty_dir

  - pushd test/test_data
  - export TEST_DATA_DIR=`pwd`
  - popd
  - pwd



before_script:
# Note: nginx appears to have been started on install - so, reload should work
  - sudo cp ${TEST_DATA_DIR}/test_config_data/mctest.localhost.conf /etc/nginx/conf.d/
  - sudo nginx -s reload
  - cd $MC_CLONE_DIR
  - rethinkdb --driver-port $MCDB_PORT --cluster-port $RETHINKDB_CLUSTER_PORT --http-port $RETHINKDB_HTTP_PORT --daemon
  - sleep 5
  - rethinkdb restore 'test_data/test_rethinkdb_dump.tar.gz' --connect $MCDB_CONNECTION --force
  - sleep 5

  - cd backend
  - pushd scripts/templates
  - ./run.sh
  - popd

  - gulp build-lib
  - gulp build-mcapi-server
  - sleep 5
  - node sbin/mcapi/mcapi.js -p $MCAPI_SERVER_PORT > ${MC_LOG_DIR}/mcapi.out.${SERVERTYPE} 2>&1&
  - sleep 5
  - cd $MC_PYTHON_API_DIR
  - pwd
  - pip install coverage
  - python setup.py install
  - cp test/test_data/test_config_data/travisconfig.json ~/.materialscommons/config.json

  - sleep 20
# Note: guard to prevent tests if host is not available
  - curl -o junk.txt http://mctest.localhost/api/v2/templates?apikey=totally-bogus
  - grep 'otype' junk.txt

script:
  - pytest test -rsx
#  - -rsx to show reasons for skipping and failed tests
#  - coverage run --source mcapi,casm_mcapi,demo_project -m py.test test
#  - coverage report -m

after_failure:
  - echo ${MC_LOG_DIR}/mcapi.out.${SERVERTYPE}
  - cat ${MC_LOG_DIR}/mcapi.out.${SERVERTYPE}
