sudo: false

language: python

python:
  - 2.7

env:
  global:
    - MCDIR=/tmp/mcdir
    - MCDB_TYPE=rethinkdb
    - MCDB_NAME=materialscommons
    - MCDB_FILE=rethink_startup/rethinkdb_dump_test_data.tar.gz
    - MCDB_PORT=30815
    - MCDB_CONNECTION=localhost:$MCDB_PORT
    - RETHINKDB_CLUSTER_PORT=31815
    - RETHINKDB_HTTP_PORT=8090

install:
  - git clone https://github.com/materials-commons/materialscommons.org.git
  - pushd materialscommons.org/backend
  - mcservers start -u
  - popd
  - cd python
  - pip install -r requirements.txt
  - python setup.py install --user

script:
  - pytest

